### ISSUE TITLE
Crashed when a train hit mobs

### ISSUE THREAD

**Issue by LucilleThurns** [DakotaPride/create-garnished#20] opened 2023-10-11 09:56 UTC
Description: Exception in server tick loop

java.lang.ClassCastException: class com.simibubi.create.content.trains.entity.CarriageContraptionEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (com.simibubi.create.content.trains.entity.CarriageContraptionEntity is in module create@0.5.1.e of loader 'TRANSFORMER' @93824eb; net.minecraft.world.entity.LivingEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @93824eb)
	at net.minecraft.world.entity.LivingEntity.handler$zba000$d(LivingEntity.java:3562) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:garnished.mixins.json:LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6515_(LivingEntity.java) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:garnished.mixins.json:LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6475_(LivingEntity.java:1620) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:garnished.mixins.json:LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:garnished.mixins.json:LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.animal.Animal.m_6469_(Animal.java:76) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at com.simibubi.create.content.contraptions.ContraptionCollider.handleDamageFromTrain(ContraptionCollider.java:547) ~[create-1.20.1-0.5.1.e.jar%23159!/:0.5.1.e] {re:mixin,re:classloading}
	at com.simibubi.create.content.contraptions.ContraptionCollider.collideEntities(ContraptionCollider.java:363) ~[create-1.20.1-0.5.1.e.jar%23159!/:0.5.1.e] {re:mixin,re:classloading}
	at com.simibubi.create.content.contraptions.ContraptionHandler.tick(ContraptionHandler.java:55) ~[create-1.20.1-0.5.1.e.jar%23159!/:0.5.1.e] {re:mixin,re:classloading}
	at com.simibubi.create.foundation.events.CommonEvents.onServerWorldTick(CommonEvents.java:96) ~[create-1.20.1-0.5.1.e.jar%23159!/:0.5.1.e] {re:classloading}
	at com.simibubi.create.foundation.events.__CommonEvents_onServerWorldTick_LevelTickEvent.invoke(.dynamic) ~[create-1.20.1-0.5.1.e.jar%23159!/:0.5.1.e] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by DakotaPride** [comment] 2023-10-11 11:38
Please use pastebin.com in the future for providing crash reports and/or latest.log files. Please also provide the version of garnished that you are using and the mod loader.

**Comment by DakotaPride** [comment] 2023-10-15 00:05
This post has been marked as "inactive." If you are still experiencing this issue, please provide the information asked for in the previous comment, thank you.

**Comment by DakotaPride** [comment] 2023-10-15 04:58
(as a sidenote, Garnished is currently incompatible with Create 0.5.1e)

**Comment by DakotaPride** [comment] 2023-10-15 15:39
Should be fixed with v1.1, will notify once released

**Comment by naomieow** [comment] 2023-10-15 21:37
This is caused by the following two identical lines in `LivingEntityMixin` as `CarriageContraptionEntity` is not an instance of `LivingEntity` so the game crashes when the cast is attempted. https://github.com/DakotaPride/create-garnished/blob/137f479532af6af5f375bc6eb19aad7d27146557/src/main/java/net/dakotapride/garnished/mixin/LivingEntityMixin.java#L55
https://github.com/DakotaPride/create-garnished/blob/137f479532af6af5f375bc6eb19aad7d27146557/src/main/java/net/dakotapride/garnished/mixin/LivingEntityMixin.java#L74

**Comment by DakotaPride** [comment] 2023-10-15 21:46
@naomieow 
I am aware of this already. I just haven't pushed this fix to the fabric repository yet (or 1.19.2 branches) but you can look at the forge 1.20.1 branch LivingEntityMixin class to view the change.

**Comment by naomieow** [comment] 2023-10-15 22:58
Awesome! Ran into this crash on my GF's sever and just wanted to make sure you were aware of the issue <3

Edit: the rest of my sentence because I forgot it 😭

**Comment by DakotaPride** [comment] 2023-10-16 22:08
> Awesome! Ran into this crash on my GF's sever and just wanted to make sure you were aware of the issue <3
> 
> Edit: the rest of my sentence because I forgot it 😭

Yeah, apologies for the issue to begin with! I'm just waiting for some minor translations and it should be released soon after! ("immediately" on modrinth, and then hopefully soon on Curseforge. It can take a while for those files to get accepted lol)

**Comment by naomieow** [comment] 2023-10-17 00:08
Yeah I know the pain of waiting for stuff to get approved 🙃

**Comment by LucilleThurns** [comment] 2023-10-17 09:09
> Please use pastebin.com in the future for providing crash reports and/or latest.log files. Please also provide the version of garnished that you are using and the mod loader.

sorry for not including this, first time using github

**Comment by DakotaPride** [comment] 2023-10-18 12:05
This should now be fixed in the latest version, you can find them both on [Modrinth](https://modrinth.com/mod/create-garnished/versions) and [Curseforge](www.curseforge.com/minecraft/mc-mods/garnished/files)

**Closed as completed by DakotaPride** 2023-10-18 12:05 UTC
Labels: bug
