### ISSUE TITLE
forge/neoforge mix up

### ISSUE THREAD

**Issue by superblast1** [DakotaPride/create-garnished#78] opened 2024-12-16 18:08 UTC
in the latest update the files marked forge are actually neoforge files and that breaks the mod

**Comment by superblast1** [comment] 2024-12-16 18:09
this is in 1.20.1 btw

**Comment by DakotaPride** [comment] 2024-12-17 02:53
It definitely shouldn't break the mod. All files are either marked as Fabric/Quilt or Neoforge/Forge, so updating to a newer version of the mod should not be the cause of your issue. Please provide more details than "it's broken", provide logs or crash reports if applicable, more details help me fix whatever issue you're experiencing.

**Comment by DakotaPride** [comment] 2024-12-17 02:53
More than likely, something else is breaking your instance

**Comment by superblast1** [comment] 2024-12-18 20:16
![image](https://github.com/user-attachments/assets/c9eef885-3a7f-46c9-95ed-a39b61bce844)

it works on its own so i dont know what the problem is but also i wanted to show you why i thought the issue was forge/neoforge

edit this is in a forge instance

**Comment by DakotaPride** [comment] 2024-12-19 05:07
so what exactly is the issue that you're experiencing?

**Comment by DakotaPride** [comment] 2024-12-24 16:49
I'm closing this issue due to inactivity, if you're still experiencing the issue, please lmk and provide actual information regarding the issue aside from "it doesn't work"

**Closed as completed by DakotaPride** 2024-12-24 16:49 UTC
